[build]
  # Define the build command that will install dependencies and build both the server and client
  build = """
    # Install dependencies for the server and client
    cd server && npm install && cd ../client && npm install
    
    # Build the frontend
    cd client && npm run build
    
    # Return to the server directory
    cd ../server
  """

[start]
  # Start the application after the build process
  start = "node index.js"